server:
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/MedicineManager
    username: postgres
    password: ahmedroot

  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
    user: postgres
    password: ahmedroot

logging:
  level:
    org.flywaydb: trace
